name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cache-vcpkg
      id: cache-vcpkg
      uses: actions/cache@v2
      with:
        path: ~/.cache
        key: ${{runner.os}}-vcpkg
    #- uses: lukka/run-vcpkg@v4
    #  with:
    #    vcpkgArguments: 'boost-container-hash boost-algorithm'
    #    setupOnly: true
    #    vcpkgDirectory: '${VCPKG_INSTALLATION_ROOT}'
    - name: install boost-container-hash
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: |
         vcpkg install boost-container-hash
         vcpkg install boost-algorithm
    - name: cmake build
      run: |
          cmake -S . -B build
    - name: build
      run: |
          cmake --build build --config Release
    #- name: Create Build Environment
    #  run: sh testall.sh
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: my-artifact
    #
    #    path: tests/grade
