name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: sh setup.sh
  test1:
     needs: setup
     steps:
             -run: sh test 1a     

