name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: lukka/run-vcpkg@v4
      with:
        vcpkgArguments: 'boost-container-hash boost-algorithm'
        vcpkgDirectory: '${VCPKG_INSTALLATION_ROOT}'
    #- name: install boost-container-hash
    #  run: |
    #     vcpkg install boost-container-hash
    #     vcpkg install boost-algorithm
    - name: cmake build
      run: |
          cmake -S . -B build
    - name: build
      run: |
          cmake --build build --config Release
    #- name: Create Build Environment
    #  run: sh testall.sh
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: my-artifact
    #
    #    path: tests/grade
