name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install boost-container-hash
      run: |
         vcpkg install boost-container-hash
    - name: cmake build
      run: |
          cmake -S . -B build
    - name: build
          cmake --build build --config Release
    #- name: Create Build Environment
    #  run: sh testall.sh
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: my-artifact
    #
    #    path: tests/grade
