on:
  push
   
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: write to file
        run: /bin/echo "using javascript" > output
#      - uses: actions/upload-artifact@v2
#        with:
#           name: artifact
#           path: output

      - uses: actions/github-script@v3
        id: set-result
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var fs=require('fs')
            var data=fs.readFileSync('output','utf8')
            github.issues.createComment({
              issue_number: 3,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Good. Your score is!'
            })
            github.issues.create({
                 owner:context.repo.owner,
                 repo: context.repo.repo,
                 title: "new issue from action"
                  });
            const msg= "using a constant"
            github.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: 7,
                  body: data
                  })
#          result-encoding: string
#      - name: get result
#        run: echo "${{steps.set-result.outputs.result}}"
    
